import type { Metadata } from "next";
import { Kanit, Hind_Siliguri, Outfit } from "next/font/google";
import "@/styles/globals.css";
import CustomCursor from "@/lib";
import LenisSmooth from "@/lib/Lenis";
import SmoothScrollbars from "@/lib/SmoothScrollbars";

const kanit = Kanit({ 
  subsets: ["latin"], 
  weight: ['400', '500', '600', '700', '800', '900' ],
  variable: '--font-kanit', 
});
const hind = Hind_Siliguri({ 
    subsets: ["latin"], 
    weight: ['400', '500', '600', '700' ],
    variable: '--font-hind', 
  });

const outfit = Outfit({ 
    subsets: ["latin"], 
    weight: [ '100', '200', '300', '400', '500', '600', '700', '800', '900' ],
    variable: '--font-outfit', 
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ kanit.variable } ${ hind.variable } ${ outfit.variable } smooth-scrollbar`}>
        {/* <CustomCursor /> */}
        <SmoothScrollbars />
        <LenisSmooth />
          {children}
      </body>
    </html>
  );
}
